### PR TITLE
Basic support for calling FRED as a service

### PR DESCRIPTION
**Pull request by jmandel**
This adds support for calling FRED via `postMessage`. It's not very elegantly implemented, so @gotdan please feel free to share pointers/advice about how I can better incorporate this, and I'll clean it up before you merge.

### CODE REVIEW

**Comment by gotdan** [comment]
@jmandel - I think the implementation looks fine, but I created a branch to see what it would look like if we put all of the messaging functions into a navbar component (https://github.com/smart-on-fhir/fred/tree/postmessage). I like that it restricts the reactions to things that modify the data store - what are your thoughts?

**Comment by jmandel** [comment]
Well, that looks/works great. I also like that you no longer flash the load screen in remote mode :-)

Only possible downside is there's no longer a way to just... paste in a wholesale-new JSON snipped within FRED to replace the resource (which was possible in my hackier integration).

**Comment by gotdan** [comment]
Fair point - added the open dialog back to the remote navbar

**Comment by jmandel** [comment]
Cool! Then good to go from my POV.

**Pull request merged**
